### ISSUE TITLE
Rack-timeout is not tested

### ISSUE THREAD

**Issue by Ferdy89** [ankane/the-ultimate-guide-to-ruby-timeouts#12]
It says in the `README` that

> All [gems] have been tested

But in reality (at least) [`rack-timeout`](https://github.com/heroku/rack-timeout) is not. Two solutions come to mind:
- Test the gem
- Change the language to something like "Some of these gems are tested here"

The latter looks simpler to me.

This might not look like a big deal but it might give certain people absolute confidence when using the gem. It's been [two years since they've wanted to test the gem](https://github.com/heroku/rack-timeout/issues/52) but they haven't.

**Comment by biow0lf** [comment]
I can confirm that `rack-timeout` is works. Or question about `rack-timeout` itself tests?

**Comment by Ferdy89** [comment]
@biow0lf I'm not saying it doesn't work, I'm saying it doesn't have any automated tests (that I've seen). As I pointed out, even they're concerned about the lack of tests of their gem

**Comment by ankane** [comment]
Hey @Ferdy89, I've tested the few gems that don't have automated tests manually. I don't think the language needs updated.
