### ISSUE TITLE
No guide for Net::SSH.exec!

### ISSUE THREAD

**Issue by yn** [ankane/the-ultimate-guide-to-ruby-timeouts#13]
Net::SSH.start has a timeout: argument, but Net::SSH.exec! does not. Is there a work around that doesn't use Ruby timeout for that?

**Comment by ankane** [comment]
Unsure, but maybe someone else will know.

**Comment by ankane** [comment]
Doesn't look like it.

**Comment by hackhowtofaq** [comment]
Sorry for bringing this up....
but I cannot believe that there is no answer for this.

So what is the correct way to timeout and kill a remote cmd? Anyone?
I have some solutions but I am not sure if they are 100% correct in edge cases.

**Comment by yn** [comment]
Well, we can try to figure it out collaboratively on this thread. Paste in
your solution and corner cases?

**Comment by hackhowtofaq** [comment]
I ll write a blog post about this and comment here when ready.
I am still testing my solution... 

What I am actually doing is starting 2 threads: 

- The first `exec!` the actual command
- The second is waiting until a timeout value is reached 

If the timeout period expires prior to completion of the first,
a new `exec!` is performed in the second thread to kill the remote cmd.

**Comment by yn** [comment]
thats not going to work if the network becomes congested. What you really
want to do is to disconnect the socket; a correct solution would not use
exec! But would instead exec and then wait in a loop.

**Comment by hackhowtofaq** [comment]
That is not a problem for me right now, but 
you can `exec` and wait for timeout, and then start the 2nd thread.... problem solved

I am heavily testing my solution now, wait for my results.

I am doing this in parallel in 10 servers and it is working without a problem....
You should use a thread-pool at some point.... I am not expecting this to work on 1000 connections at the same time ;)
