### ISSUE TITLE
PostgreSQL statement_timeout [question]

### ISSUE THREAD

**Issue by ohaddahan** [ankane/the-ultimate-guide-to-ruby-timeouts#20]
I'm trying to run:

```
sql_string = "SET LOCAL statement_timeout = 1; <SOME LONG QUERY>"
results = ActiveRecord::Base.connection.execute(sql_string)

```

If I added `BEGIN; SET LOCAL statement_timeout = 1; <SOME LONG QUERY> ; COMMIT;` , I'm not getting any return value from `ActiveRecord::Base.connection.execute(sql_string)`.

Expecting it to timeout , but it seem to finish the query.
Anything that I'm missing?

**Comment by ankane** [comment]
Hey @ohaddahan, not sure it'll work that way. Try something like:

```ruby
results = nil
ActiveRecord::Base.transaction do
  ActiveRecord::Base.connection.execute("SET LOCAL statement_timeout = 1")
  results = ActiveRecord::Base.connection.execute(sql_string)
end
```

**Comment by ohaddahan** [comment]
@ankane exactly what I was looking for , thanks.
