### ISSUE TITLE
postgres connect_timeout

### ISSUE THREAD

**Issue by deepeeess** [ankane/the-ultimate-guide-to-ruby-timeouts#27]
not sure if this needs to be fixed but libpq recommends not using a connect_timeout under 2 seconds, your example is 1 second.

https://www.postgresql.org/docs/9.1/libpq-connect.html

**Comment by ankane** [comment]
Hey @deepeeess, thanks for the suggestion. See #22

**Comment by deepeeess** [comment]
Sorry I actually went through the search results to look for dupes, missed it.

**Comment by ankane** [comment]
No worries
