### ISSUE TITLE
Timeout Recommendations

### ISSUE THREAD

**Issue by ogirginc** [ankane/the-ultimate-guide-to-ruby-timeouts#31]
Apologies in advance, if this obvious to others but it is not clear to me; does this guide just show how to set timeouts or the numbers used in examples are considered as best practices? For example, [postgresql](https://github.com/ankane/the-ultimate-guide-to-ruby-timeouts#postgresql)'s `STATEMENT_TIMEOUT` is set to `90`. Is there a specific reason for it or was it just a sensible number?

**Comment by ankane** [comment]
Hey @ogirginc, the guide just shows how to set timeouts. You'll want to customize it to your application.

**Comment by ogirginc** [comment]
Thanks, @ankane 👍
